{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "modular-volume",
   "metadata": {},
   "source": [
    "# Dropout Regularization \n",
    "* A simple and powerful regularization for neural networks and deep learning models is **dropout**.\n",
    "* Dropout is a technique where randomly selected neurons are ignored during training.\n",
    "* This means that their contribution to the activation of downstream neurons is temporarily removed on the forward pass and any weight updates are not applied to the neuron on the backward pass."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "stuffed-interval",
   "metadata": {},
   "source": [
    "## 1. Dropout Regularization in Keras\n",
    "* Dropout is only used during the training of a model and is not used when evaluating the skill of the model."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "endless-bobby",
   "metadata": {},
   "source": [
    "## 1.1 Using Dropout on the Visible Layer\n",
    "* The dropout rate is set to 20% meaning one in five inputs will be randomly excluded from each update cycle.\n",
    "* A constraint is imposed on the weights for each hidden layer,ensuring that the maximum norm of the weights does not exceed a value of 3."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "id": "serial-midwest",
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Visible: nan% (nan%)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py:614: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/usr/local/lib/python3.7/dist-packages/sklearn/pipeline.py\", line 346, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/keras/wrappers/scikit_learn.py\", line 223, in fit\n",
      "    return super(KerasClassifier, self).fit(x, y, **kwargs)\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/keras/wrappers/scikit_learn.py\", line 157, in fit\n",
      "    self.model = self.build_fn(**self.filter_sk_params(self.build_fn))\n",
      "  File \"<ipython-input-16-c7b1dd241f6e>\", line 40, in create_model\n",
      "    model.add(Dense(60,activation='relu',W_constraint=maxnorm(3)))\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/keras/layers/core.py\", line 1158, in __init__\n",
      "    activity_regularizer=activity_regularizer, **kwargs)\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/training/tracking/base.py\", line 517, in _method_wrapper\n",
      "    result = method(self, *args, **kwargs)\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py\", line 340, in __init__\n",
      "    generic_utils.validate_kwargs(kwargs, allowed_kwargs)\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/keras/utils/generic_utils.py\", line 808, in validate_kwargs\n",
      "    raise TypeError(error_message, kwarg)\n",
      "TypeError: ('Keyword argument not understood:', 'W_constraint')\n",
      "\n",
      "  FitFailedWarning)\n",
      "/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py:614: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/usr/local/lib/python3.7/dist-packages/sklearn/pipeline.py\", line 346, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/keras/wrappers/scikit_learn.py\", line 223, in fit\n",
      "    return super(KerasClassifier, self).fit(x, y, **kwargs)\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/keras/wrappers/scikit_learn.py\", line 157, in fit\n",
      "    self.model = self.build_fn(**self.filter_sk_params(self.build_fn))\n",
      "  File \"<ipython-input-16-c7b1dd241f6e>\", line 40, in create_model\n",
      "    model.add(Dense(60,activation='relu',W_constraint=maxnorm(3)))\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/keras/layers/core.py\", line 1158, in __init__\n",
      "    activity_regularizer=activity_regularizer, **kwargs)\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/training/tracking/base.py\", line 517, in _method_wrapper\n",
      "    result = method(self, *args, **kwargs)\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py\", line 340, in __init__\n",
      "    generic_utils.validate_kwargs(kwargs, allowed_kwargs)\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/keras/utils/generic_utils.py\", line 808, in validate_kwargs\n",
      "    raise TypeError(error_message, kwarg)\n",
      "TypeError: ('Keyword argument not understood:', 'W_constraint')\n",
      "\n",
      "  FitFailedWarning)\n",
      "/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py:614: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/usr/local/lib/python3.7/dist-packages/sklearn/pipeline.py\", line 346, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/keras/wrappers/scikit_learn.py\", line 223, in fit\n",
      "    return super(KerasClassifier, self).fit(x, y, **kwargs)\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/keras/wrappers/scikit_learn.py\", line 157, in fit\n",
      "    self.model = self.build_fn(**self.filter_sk_params(self.build_fn))\n",
      "  File \"<ipython-input-16-c7b1dd241f6e>\", line 40, in create_model\n",
      "    model.add(Dense(60,activation='relu',W_constraint=maxnorm(3)))\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/keras/layers/core.py\", line 1158, in __init__\n",
      "    activity_regularizer=activity_regularizer, **kwargs)\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/training/tracking/base.py\", line 517, in _method_wrapper\n",
      "    result = method(self, *args, **kwargs)\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py\", line 340, in __init__\n",
      "    generic_utils.validate_kwargs(kwargs, allowed_kwargs)\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/keras/utils/generic_utils.py\", line 808, in validate_kwargs\n",
      "    raise TypeError(error_message, kwarg)\n",
      "TypeError: ('Keyword argument not understood:', 'W_constraint')\n",
      "\n",
      "  FitFailedWarning)\n",
      "/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py:614: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/usr/local/lib/python3.7/dist-packages/sklearn/pipeline.py\", line 346, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/keras/wrappers/scikit_learn.py\", line 223, in fit\n",
      "    return super(KerasClassifier, self).fit(x, y, **kwargs)\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/keras/wrappers/scikit_learn.py\", line 157, in fit\n",
      "    self.model = self.build_fn(**self.filter_sk_params(self.build_fn))\n",
      "  File \"<ipython-input-16-c7b1dd241f6e>\", line 40, in create_model\n",
      "    model.add(Dense(60,activation='relu',W_constraint=maxnorm(3)))\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/keras/layers/core.py\", line 1158, in __init__\n",
      "    activity_regularizer=activity_regularizer, **kwargs)\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/training/tracking/base.py\", line 517, in _method_wrapper\n",
      "    result = method(self, *args, **kwargs)\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py\", line 340, in __init__\n",
      "    generic_utils.validate_kwargs(kwargs, allowed_kwargs)\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/keras/utils/generic_utils.py\", line 808, in validate_kwargs\n",
      "    raise TypeError(error_message, kwarg)\n",
      "TypeError: ('Keyword argument not understood:', 'W_constraint')\n",
      "\n",
      "  FitFailedWarning)\n",
      "/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py:614: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/usr/local/lib/python3.7/dist-packages/sklearn/pipeline.py\", line 346, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/keras/wrappers/scikit_learn.py\", line 223, in fit\n",
      "    return super(KerasClassifier, self).fit(x, y, **kwargs)\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/keras/wrappers/scikit_learn.py\", line 157, in fit\n",
      "    self.model = self.build_fn(**self.filter_sk_params(self.build_fn))\n",
      "  File \"<ipython-input-16-c7b1dd241f6e>\", line 40, in create_model\n",
      "    model.add(Dense(60,activation='relu',W_constraint=maxnorm(3)))\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/keras/layers/core.py\", line 1158, in __init__\n",
      "    activity_regularizer=activity_regularizer, **kwargs)\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/training/tracking/base.py\", line 517, in _method_wrapper\n",
      "    result = method(self, *args, **kwargs)\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py\", line 340, in __init__\n",
      "    generic_utils.validate_kwargs(kwargs, allowed_kwargs)\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/keras/utils/generic_utils.py\", line 808, in validate_kwargs\n",
      "    raise TypeError(error_message, kwarg)\n",
      "TypeError: ('Keyword argument not understood:', 'W_constraint')\n",
      "\n",
      "  FitFailedWarning)\n",
      "/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py:614: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/usr/local/lib/python3.7/dist-packages/sklearn/pipeline.py\", line 346, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/keras/wrappers/scikit_learn.py\", line 223, in fit\n",
      "    return super(KerasClassifier, self).fit(x, y, **kwargs)\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/keras/wrappers/scikit_learn.py\", line 157, in fit\n",
      "    self.model = self.build_fn(**self.filter_sk_params(self.build_fn))\n",
      "  File \"<ipython-input-16-c7b1dd241f6e>\", line 40, in create_model\n",
      "    model.add(Dense(60,activation='relu',W_constraint=maxnorm(3)))\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/keras/layers/core.py\", line 1158, in __init__\n",
      "    activity_regularizer=activity_regularizer, **kwargs)\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/training/tracking/base.py\", line 517, in _method_wrapper\n",
      "    result = method(self, *args, **kwargs)\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py\", line 340, in __init__\n",
      "    generic_utils.validate_kwargs(kwargs, allowed_kwargs)\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/keras/utils/generic_utils.py\", line 808, in validate_kwargs\n",
      "    raise TypeError(error_message, kwarg)\n",
      "TypeError: ('Keyword argument not understood:', 'W_constraint')\n",
      "\n",
      "  FitFailedWarning)\n",
      "/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py:614: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/usr/local/lib/python3.7/dist-packages/sklearn/pipeline.py\", line 346, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/keras/wrappers/scikit_learn.py\", line 223, in fit\n",
      "    return super(KerasClassifier, self).fit(x, y, **kwargs)\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/keras/wrappers/scikit_learn.py\", line 157, in fit\n",
      "    self.model = self.build_fn(**self.filter_sk_params(self.build_fn))\n",
      "  File \"<ipython-input-16-c7b1dd241f6e>\", line 40, in create_model\n",
      "    model.add(Dense(60,activation='relu',W_constraint=maxnorm(3)))\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/keras/layers/core.py\", line 1158, in __init__\n",
      "    activity_regularizer=activity_regularizer, **kwargs)\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/training/tracking/base.py\", line 517, in _method_wrapper\n",
      "    result = method(self, *args, **kwargs)\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py\", line 340, in __init__\n",
      "    generic_utils.validate_kwargs(kwargs, allowed_kwargs)\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/keras/utils/generic_utils.py\", line 808, in validate_kwargs\n",
      "    raise TypeError(error_message, kwarg)\n",
      "TypeError: ('Keyword argument not understood:', 'W_constraint')\n",
      "\n",
      "  FitFailedWarning)\n",
      "/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py:614: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/usr/local/lib/python3.7/dist-packages/sklearn/pipeline.py\", line 346, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/keras/wrappers/scikit_learn.py\", line 223, in fit\n",
      "    return super(KerasClassifier, self).fit(x, y, **kwargs)\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/keras/wrappers/scikit_learn.py\", line 157, in fit\n",
      "    self.model = self.build_fn(**self.filter_sk_params(self.build_fn))\n",
      "  File \"<ipython-input-16-c7b1dd241f6e>\", line 40, in create_model\n",
      "    model.add(Dense(60,activation='relu',W_constraint=maxnorm(3)))\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/keras/layers/core.py\", line 1158, in __init__\n",
      "    activity_regularizer=activity_regularizer, **kwargs)\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/training/tracking/base.py\", line 517, in _method_wrapper\n",
      "    result = method(self, *args, **kwargs)\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py\", line 340, in __init__\n",
      "    generic_utils.validate_kwargs(kwargs, allowed_kwargs)\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/keras/utils/generic_utils.py\", line 808, in validate_kwargs\n",
      "    raise TypeError(error_message, kwarg)\n",
      "TypeError: ('Keyword argument not understood:', 'W_constraint')\n",
      "\n",
      "  FitFailedWarning)\n",
      "/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py:614: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/usr/local/lib/python3.7/dist-packages/sklearn/pipeline.py\", line 346, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/keras/wrappers/scikit_learn.py\", line 223, in fit\n",
      "    return super(KerasClassifier, self).fit(x, y, **kwargs)\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/keras/wrappers/scikit_learn.py\", line 157, in fit\n",
      "    self.model = self.build_fn(**self.filter_sk_params(self.build_fn))\n",
      "  File \"<ipython-input-16-c7b1dd241f6e>\", line 40, in create_model\n",
      "    model.add(Dense(60,activation='relu',W_constraint=maxnorm(3)))\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/keras/layers/core.py\", line 1158, in __init__\n",
      "    activity_regularizer=activity_regularizer, **kwargs)\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/training/tracking/base.py\", line 517, in _method_wrapper\n",
      "    result = method(self, *args, **kwargs)\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py\", line 340, in __init__\n",
      "    generic_utils.validate_kwargs(kwargs, allowed_kwargs)\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/keras/utils/generic_utils.py\", line 808, in validate_kwargs\n",
      "    raise TypeError(error_message, kwarg)\n",
      "TypeError: ('Keyword argument not understood:', 'W_constraint')\n",
      "\n",
      "  FitFailedWarning)\n",
      "/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py:614: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/usr/local/lib/python3.7/dist-packages/sklearn/pipeline.py\", line 346, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/keras/wrappers/scikit_learn.py\", line 223, in fit\n",
      "    return super(KerasClassifier, self).fit(x, y, **kwargs)\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/keras/wrappers/scikit_learn.py\", line 157, in fit\n",
      "    self.model = self.build_fn(**self.filter_sk_params(self.build_fn))\n",
      "  File \"<ipython-input-16-c7b1dd241f6e>\", line 40, in create_model\n",
      "    model.add(Dense(60,activation='relu',W_constraint=maxnorm(3)))\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/keras/layers/core.py\", line 1158, in __init__\n",
      "    activity_regularizer=activity_regularizer, **kwargs)\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/training/tracking/base.py\", line 517, in _method_wrapper\n",
      "    result = method(self, *args, **kwargs)\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py\", line 340, in __init__\n",
      "    generic_utils.validate_kwargs(kwargs, allowed_kwargs)\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/keras/utils/generic_utils.py\", line 808, in validate_kwargs\n",
      "    raise TypeError(error_message, kwarg)\n",
      "TypeError: ('Keyword argument not understood:', 'W_constraint')\n",
      "\n",
      "  FitFailedWarning)\n"
     ]
    }
   ],
   "source": [
    "# Example of Dropout on the Sonar Dataset: Visible Layer\n",
    "#import tensorflow \n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "from keras.models import Sequential\n",
    "from keras.layers import Dense\n",
    "from keras.layers import Dropout\n",
    "from keras.wrappers.scikit_learn import KerasClassifier\n",
    "from keras.constraints import maxnorm\n",
    "#from keras.constraints import W_constraint\n",
    "#from tensorflow.contrib.keras.python.keras.constraints import W_constraint\n",
    "from keras.optimizers import SGD\n",
    "from sklearn.model_selection import cross_val_score\n",
    "from sklearn.preprocessing import LabelEncoder\n",
    "from sklearn.model_selection import StratifiedKFold\n",
    "from sklearn.pipeline import Pipeline\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "\n",
    "# fix random seed for reproducibility\n",
    "seed = 7\n",
    "np.random.seed(seed)\n",
    "\n",
    "# loading dataset\n",
    "dataframe = pd.read_csv(\"sonar.csv\",header=None)\n",
    "dataset = dataframe.values\n",
    "\n",
    "# split into input(X) and output(Y) variables\n",
    "X = dataset[:,0:60].astype(float)\n",
    "Y = dataset[:,60]\n",
    "\n",
    "# encode class values as integers\n",
    "encoder = LabelEncoder()\n",
    "encoder.fit(Y)\n",
    "encoded_Y = encoder.transform(Y)\n",
    "\n",
    "# dropout in the input layer with weight constraint\n",
    "def create_model():\n",
    "    model = Sequential()\n",
    "    model.add(Dropout(0.2,input_shape=(60,0)))\n",
    "    model.add(Dense(60,activation='relu',W_constraint=maxnorm(3)))\n",
    "    model.add(Dense(30,activation='relu',W_constraint=maxnorm(3)))\n",
    "    model.add(Dense(1,activation='sigmoid'))\n",
    "    \n",
    "    # compile model\n",
    "    sgd = SGD(lr=0.1,momentum=0.9,decay=0.0,nesterov=False)\n",
    "    model.compile(loss='binary_crossentropy',optimizer=sgd,metrics=['accuracy'])\n",
    "    return model\n",
    "\n",
    "np.random.seed(seed)\n",
    "estimators = []\n",
    "estimators.append(('standardize',StandardScaler()))\n",
    "estimators.append(('mlp',KerasClassifier(build_fn=create_model,epochs=300,batch_size=16,verbose=0)))\n",
    "pipeline = Pipeline(estimators)\n",
    "kfold = StratifiedKFold(n_splits=10,shuffle=True,random_state=seed)\n",
    "results = cross_val_score(pipeline,X,encoded_Y,cv=kfold)\n",
    "print(\"Visible: %.2f%% (%.2f%%)\" %(results.mean()*100,results.std()*100))"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "verified-challenge",
   "metadata": {},
   "source": [
    "## 1.2 Using Dropout on Hidden Layers\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "id": "alpine-karen",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Hidden: nan% (nan%)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py:614: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/usr/local/lib/python3.7/dist-packages/sklearn/pipeline.py\", line 346, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/keras/wrappers/scikit_learn.py\", line 223, in fit\n",
      "    return super(KerasClassifier, self).fit(x, y, **kwargs)\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/keras/wrappers/scikit_learn.py\", line 157, in fit\n",
      "    self.model = self.build_fn(**self.filter_sk_params(self.build_fn))\n",
      "  File \"<ipython-input-14-422cfd35446f>\", line 32, in create_model\n",
      "    model.add(Dense(60, input_dim=60, activation='relu' ,W_constraint=maxnorm(3)))\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/keras/layers/core.py\", line 1158, in __init__\n",
      "    activity_regularizer=activity_regularizer, **kwargs)\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/training/tracking/base.py\", line 517, in _method_wrapper\n",
      "    result = method(self, *args, **kwargs)\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py\", line 340, in __init__\n",
      "    generic_utils.validate_kwargs(kwargs, allowed_kwargs)\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/keras/utils/generic_utils.py\", line 808, in validate_kwargs\n",
      "    raise TypeError(error_message, kwarg)\n",
      "TypeError: ('Keyword argument not understood:', 'W_constraint')\n",
      "\n",
      "  FitFailedWarning)\n",
      "/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py:614: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/usr/local/lib/python3.7/dist-packages/sklearn/pipeline.py\", line 346, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/keras/wrappers/scikit_learn.py\", line 223, in fit\n",
      "    return super(KerasClassifier, self).fit(x, y, **kwargs)\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/keras/wrappers/scikit_learn.py\", line 157, in fit\n",
      "    self.model = self.build_fn(**self.filter_sk_params(self.build_fn))\n",
      "  File \"<ipython-input-14-422cfd35446f>\", line 32, in create_model\n",
      "    model.add(Dense(60, input_dim=60, activation='relu' ,W_constraint=maxnorm(3)))\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/keras/layers/core.py\", line 1158, in __init__\n",
      "    activity_regularizer=activity_regularizer, **kwargs)\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/training/tracking/base.py\", line 517, in _method_wrapper\n",
      "    result = method(self, *args, **kwargs)\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py\", line 340, in __init__\n",
      "    generic_utils.validate_kwargs(kwargs, allowed_kwargs)\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/keras/utils/generic_utils.py\", line 808, in validate_kwargs\n",
      "    raise TypeError(error_message, kwarg)\n",
      "TypeError: ('Keyword argument not understood:', 'W_constraint')\n",
      "\n",
      "  FitFailedWarning)\n",
      "/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py:614: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/usr/local/lib/python3.7/dist-packages/sklearn/pipeline.py\", line 346, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/keras/wrappers/scikit_learn.py\", line 223, in fit\n",
      "    return super(KerasClassifier, self).fit(x, y, **kwargs)\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/keras/wrappers/scikit_learn.py\", line 157, in fit\n",
      "    self.model = self.build_fn(**self.filter_sk_params(self.build_fn))\n",
      "  File \"<ipython-input-14-422cfd35446f>\", line 32, in create_model\n",
      "    model.add(Dense(60, input_dim=60, activation='relu' ,W_constraint=maxnorm(3)))\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/keras/layers/core.py\", line 1158, in __init__\n",
      "    activity_regularizer=activity_regularizer, **kwargs)\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/training/tracking/base.py\", line 517, in _method_wrapper\n",
      "    result = method(self, *args, **kwargs)\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py\", line 340, in __init__\n",
      "    generic_utils.validate_kwargs(kwargs, allowed_kwargs)\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/keras/utils/generic_utils.py\", line 808, in validate_kwargs\n",
      "    raise TypeError(error_message, kwarg)\n",
      "TypeError: ('Keyword argument not understood:', 'W_constraint')\n",
      "\n",
      "  FitFailedWarning)\n",
      "/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py:614: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/usr/local/lib/python3.7/dist-packages/sklearn/pipeline.py\", line 346, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/keras/wrappers/scikit_learn.py\", line 223, in fit\n",
      "    return super(KerasClassifier, self).fit(x, y, **kwargs)\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/keras/wrappers/scikit_learn.py\", line 157, in fit\n",
      "    self.model = self.build_fn(**self.filter_sk_params(self.build_fn))\n",
      "  File \"<ipython-input-14-422cfd35446f>\", line 32, in create_model\n",
      "    model.add(Dense(60, input_dim=60, activation='relu' ,W_constraint=maxnorm(3)))\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/keras/layers/core.py\", line 1158, in __init__\n",
      "    activity_regularizer=activity_regularizer, **kwargs)\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/training/tracking/base.py\", line 517, in _method_wrapper\n",
      "    result = method(self, *args, **kwargs)\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py\", line 340, in __init__\n",
      "    generic_utils.validate_kwargs(kwargs, allowed_kwargs)\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/keras/utils/generic_utils.py\", line 808, in validate_kwargs\n",
      "    raise TypeError(error_message, kwarg)\n",
      "TypeError: ('Keyword argument not understood:', 'W_constraint')\n",
      "\n",
      "  FitFailedWarning)\n",
      "/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py:614: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/usr/local/lib/python3.7/dist-packages/sklearn/pipeline.py\", line 346, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/keras/wrappers/scikit_learn.py\", line 223, in fit\n",
      "    return super(KerasClassifier, self).fit(x, y, **kwargs)\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/keras/wrappers/scikit_learn.py\", line 157, in fit\n",
      "    self.model = self.build_fn(**self.filter_sk_params(self.build_fn))\n",
      "  File \"<ipython-input-14-422cfd35446f>\", line 32, in create_model\n",
      "    model.add(Dense(60, input_dim=60, activation='relu' ,W_constraint=maxnorm(3)))\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/keras/layers/core.py\", line 1158, in __init__\n",
      "    activity_regularizer=activity_regularizer, **kwargs)\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/training/tracking/base.py\", line 517, in _method_wrapper\n",
      "    result = method(self, *args, **kwargs)\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py\", line 340, in __init__\n",
      "    generic_utils.validate_kwargs(kwargs, allowed_kwargs)\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/keras/utils/generic_utils.py\", line 808, in validate_kwargs\n",
      "    raise TypeError(error_message, kwarg)\n",
      "TypeError: ('Keyword argument not understood:', 'W_constraint')\n",
      "\n",
      "  FitFailedWarning)\n",
      "/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py:614: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/usr/local/lib/python3.7/dist-packages/sklearn/pipeline.py\", line 346, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/keras/wrappers/scikit_learn.py\", line 223, in fit\n",
      "    return super(KerasClassifier, self).fit(x, y, **kwargs)\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/keras/wrappers/scikit_learn.py\", line 157, in fit\n",
      "    self.model = self.build_fn(**self.filter_sk_params(self.build_fn))\n",
      "  File \"<ipython-input-14-422cfd35446f>\", line 32, in create_model\n",
      "    model.add(Dense(60, input_dim=60, activation='relu' ,W_constraint=maxnorm(3)))\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/keras/layers/core.py\", line 1158, in __init__\n",
      "    activity_regularizer=activity_regularizer, **kwargs)\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/training/tracking/base.py\", line 517, in _method_wrapper\n",
      "    result = method(self, *args, **kwargs)\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py\", line 340, in __init__\n",
      "    generic_utils.validate_kwargs(kwargs, allowed_kwargs)\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/keras/utils/generic_utils.py\", line 808, in validate_kwargs\n",
      "    raise TypeError(error_message, kwarg)\n",
      "TypeError: ('Keyword argument not understood:', 'W_constraint')\n",
      "\n",
      "  FitFailedWarning)\n",
      "/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py:614: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/usr/local/lib/python3.7/dist-packages/sklearn/pipeline.py\", line 346, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/keras/wrappers/scikit_learn.py\", line 223, in fit\n",
      "    return super(KerasClassifier, self).fit(x, y, **kwargs)\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/keras/wrappers/scikit_learn.py\", line 157, in fit\n",
      "    self.model = self.build_fn(**self.filter_sk_params(self.build_fn))\n",
      "  File \"<ipython-input-14-422cfd35446f>\", line 32, in create_model\n",
      "    model.add(Dense(60, input_dim=60, activation='relu' ,W_constraint=maxnorm(3)))\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/keras/layers/core.py\", line 1158, in __init__\n",
      "    activity_regularizer=activity_regularizer, **kwargs)\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/training/tracking/base.py\", line 517, in _method_wrapper\n",
      "    result = method(self, *args, **kwargs)\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py\", line 340, in __init__\n",
      "    generic_utils.validate_kwargs(kwargs, allowed_kwargs)\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/keras/utils/generic_utils.py\", line 808, in validate_kwargs\n",
      "    raise TypeError(error_message, kwarg)\n",
      "TypeError: ('Keyword argument not understood:', 'W_constraint')\n",
      "\n",
      "  FitFailedWarning)\n",
      "/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py:614: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/usr/local/lib/python3.7/dist-packages/sklearn/pipeline.py\", line 346, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/keras/wrappers/scikit_learn.py\", line 223, in fit\n",
      "    return super(KerasClassifier, self).fit(x, y, **kwargs)\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/keras/wrappers/scikit_learn.py\", line 157, in fit\n",
      "    self.model = self.build_fn(**self.filter_sk_params(self.build_fn))\n",
      "  File \"<ipython-input-14-422cfd35446f>\", line 32, in create_model\n",
      "    model.add(Dense(60, input_dim=60, activation='relu' ,W_constraint=maxnorm(3)))\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/keras/layers/core.py\", line 1158, in __init__\n",
      "    activity_regularizer=activity_regularizer, **kwargs)\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/training/tracking/base.py\", line 517, in _method_wrapper\n",
      "    result = method(self, *args, **kwargs)\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py\", line 340, in __init__\n",
      "    generic_utils.validate_kwargs(kwargs, allowed_kwargs)\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/keras/utils/generic_utils.py\", line 808, in validate_kwargs\n",
      "    raise TypeError(error_message, kwarg)\n",
      "TypeError: ('Keyword argument not understood:', 'W_constraint')\n",
      "\n",
      "  FitFailedWarning)\n",
      "/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py:614: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/usr/local/lib/python3.7/dist-packages/sklearn/pipeline.py\", line 346, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/keras/wrappers/scikit_learn.py\", line 223, in fit\n",
      "    return super(KerasClassifier, self).fit(x, y, **kwargs)\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/keras/wrappers/scikit_learn.py\", line 157, in fit\n",
      "    self.model = self.build_fn(**self.filter_sk_params(self.build_fn))\n",
      "  File \"<ipython-input-14-422cfd35446f>\", line 32, in create_model\n",
      "    model.add(Dense(60, input_dim=60, activation='relu' ,W_constraint=maxnorm(3)))\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/keras/layers/core.py\", line 1158, in __init__\n",
      "    activity_regularizer=activity_regularizer, **kwargs)\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/training/tracking/base.py\", line 517, in _method_wrapper\n",
      "    result = method(self, *args, **kwargs)\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py\", line 340, in __init__\n",
      "    generic_utils.validate_kwargs(kwargs, allowed_kwargs)\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/keras/utils/generic_utils.py\", line 808, in validate_kwargs\n",
      "    raise TypeError(error_message, kwarg)\n",
      "TypeError: ('Keyword argument not understood:', 'W_constraint')\n",
      "\n",
      "  FitFailedWarning)\n",
      "/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py:614: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/usr/local/lib/python3.7/dist-packages/sklearn/pipeline.py\", line 346, in fit\n",
      "    self._final_estimator.fit(Xt, y, **fit_params_last_step)\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/keras/wrappers/scikit_learn.py\", line 223, in fit\n",
      "    return super(KerasClassifier, self).fit(x, y, **kwargs)\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/keras/wrappers/scikit_learn.py\", line 157, in fit\n",
      "    self.model = self.build_fn(**self.filter_sk_params(self.build_fn))\n",
      "  File \"<ipython-input-14-422cfd35446f>\", line 32, in create_model\n",
      "    model.add(Dense(60, input_dim=60, activation='relu' ,W_constraint=maxnorm(3)))\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/keras/layers/core.py\", line 1158, in __init__\n",
      "    activity_regularizer=activity_regularizer, **kwargs)\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/training/tracking/base.py\", line 517, in _method_wrapper\n",
      "    result = method(self, *args, **kwargs)\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py\", line 340, in __init__\n",
      "    generic_utils.validate_kwargs(kwargs, allowed_kwargs)\n",
      "  File \"/home/kuluruvineeth/.local/lib/python3.7/site-packages/tensorflow/python/keras/utils/generic_utils.py\", line 808, in validate_kwargs\n",
      "    raise TypeError(error_message, kwarg)\n",
      "TypeError: ('Keyword argument not understood:', 'W_constraint')\n",
      "\n",
      "  FitFailedWarning)\n"
     ]
    }
   ],
   "source": [
    "# Example of Dropout on the Sonar Dataset: Hidden Layer\n",
    "import numpy\n",
    "import pandas\n",
    "from keras.models import Sequential\n",
    "from keras.layers import Dense\n",
    "from keras.layers import Dropout\n",
    "from keras.wrappers.scikit_learn import KerasClassifier\n",
    "from keras.constraints import maxnorm\n",
    "from keras.optimizers import SGD\n",
    "from sklearn.model_selection import cross_val_score\n",
    "from sklearn.preprocessing import LabelEncoder\n",
    "from sklearn.model_selection import StratifiedKFold\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "from sklearn.pipeline import Pipeline\n",
    "# fix random seed for reproducibility\n",
    "seed = 7\n",
    "numpy.random.seed(seed)\n",
    "# load dataset\n",
    "dataframe = pandas.read_csv(\"sonar.csv\", header=None)\n",
    "dataset = dataframe.values\n",
    "# split into input (X) and output (Y) variables\n",
    "X = dataset[:,0:60].astype(float)\n",
    "Y = dataset[:,60]\n",
    "# encode class values as integers\n",
    "encoder = LabelEncoder()\n",
    "encoder.fit(Y)\n",
    "encoded_Y = encoder.transform(Y)\n",
    "# dropout in hidden layers with weight constraint\n",
    "def create_model():\n",
    "    # create model\n",
    "    model = Sequential()\n",
    "    model.add(Dense(60, input_dim=60, activation='relu' ,W_constraint=maxnorm(3)))\n",
    "    model.add(Dropout(0.2))\n",
    "    model.add(Dense(30, activation='relu' , W_constraint=maxnorm(3)))\n",
    "    model.add(Dropout(0.2))\n",
    "    model.add(Dense(1, activation='sigmoid' ))\n",
    "    # Compile model\n",
    "    sgd = SGD(lr=0.1, momentum=0.9, decay=0.0, nesterov=False)\n",
    "    model.compile(loss='binary_crossentropy' , optimizer=sgd, metrics=[ 'accuracy' ])\n",
    "    return model\n",
    "numpy.random.seed(seed)\n",
    "estimators = []\n",
    "estimators.append(('standardize' , StandardScaler()))\n",
    "estimators.append(('mlp' , KerasClassifier(build_fn=create_model, nb_epoch=300,\n",
    "batch_size=16, verbose=0)))\n",
    "pipeline = Pipeline(estimators)\n",
    "kfold = StratifiedKFold(n_splits=10, shuffle=True, random_state=seed)\n",
    "results = cross_val_score(pipeline, X, encoded_Y, cv=kfold)\n",
    "print(\"Hidden: %.2f%% (%.2f%%)\" % (results.mean()*100, results.std()*100))"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "comprehensive-desire",
   "metadata": {},
   "source": [
    "# Summary\n",
    "* Use dropout on larger network.\n",
    "* Use dropout on input as well as hidden layers.\n",
    "* Use a large learning rate with decay and a large momentum.\n",
    "* Constrain the size of the network weights.\n",
    "\n",
    "* Finally discovered the dropout regularization technique for deep learning models."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "canadian-electricity",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
